backend:
  branch: master
  name: git-gateway

media_folder: "/media/"
public_folder: "/media/"

local_backend: true
collections:
  - name: "categories"
    label: "Categories"
    folder: "src/categories/"
    editor:
      preview: false
    create: true
    files:
      file: "src/categories/categories.md"
      fields:
        - { label: "Category Code", name: "cat_code", widget: "string" }
        - { label: "Category Name", name: "cat_name", widget: "string" }

        # New field with buttons
        - label: "Download JSON Files"
          name: "download_json"
          widget: "object"
          fields:
            - {
                label: "Button 1 (Download Link)",
                name: "button1",
                widget: "string",
                hint: "Link to the first JSON file",
              }
            - {
                label: "Button 2 (Download Link)",
                name: "button2",
                widget: "string",
                hint: "Link to the second JSON file",
              }

    # Add an array of static categories here
  #   static_categories:
  #     - category_name: "CCG"
  #     - category_name: "KITAC"
  #     - category_name: "FBSAC"
  #     - category_name: "KITEQ"
  #     - category_name: "KSTAC"
  #     - category_name: "KTEQP"
  #     - category_name: "KITUN"
  #     - category_name: "HKAC"
  #     - category_name: "GEN"
  #     - category_name: "SNTZP"
  #     - category_name: "JOB WORK"
  #     - category_name: "FBSBQT"
  #     - category_name: "KITEC"
  #     - category_name: "FBEQP"
  #     - category_name: "FBBQT"
  #     - category_name: "KITCHEN UNIFORM"
  #     - category_name: "TILES"

  # - name: "variations"
  #   label: "Variations"
  #   folder: "src/variations"
  #   create: true
  #   fields:
  #     - { label: "Variation Name", name: "variation_name", widget: "string" }
  #     - { label: "Price", name: "price", widget: "number" }
  #     - { label: "Attributes", name: "attributes", widget: "string" }
